class TypeTable:
    def __init__(self):
        self.tabla = {
    "Normal": {
        "Normal": 1,
        "Fuego": 1,
        "Agua": 1,
        "Planta": 1,
        "Eléctrico": 1,
        "Hielo": 1,
        "Lucha": 1,
        "Veneno": 1,
        "Tierra": 1,
        "Volador": 1,
        "Psíquico": 1,
        "Bicho": 1,
        "Roca": 0.5,
        "Fantasma": 0,
        "Dragón": 1,
        "Siniestro": 1,
        "Acero": 0.5  
    },
    "Fuego": {
        "Normal": 1,
        "Fuego": 0.5,
        "Agua": 0.5,
        "Planta": 2,
        "Eléctrico": 1,
        "Hielo": 2,
        "Lucha": 1,
        "Veneno": 1,
        "Tierra": 1,
        "Volador": 1,
        "Psíquico": 1,
        "Bicho": 2,
        "Roca": 0.5,
        "Fantasma": 1,
        "Dragón": 0.5,
        "Siniestro": 1,
        "Acero": 2
    },
    "Agua": {
        "Normal": 1,
        "Fuego": 2,
        "Agua": 0.5,
        "Planta": 0.5,
        "Eléctrico": 1,
        "Hielo": 1,
        "Lucha": 1,
        "Veneno": 1,
        "Tierra": 2,
        "Volador": 1,
        "Psíquico": 1,
        "Bicho": 1,
        "Roca": 2,
        "Fantasma": 1,
        "Dragón": 0.5,
        "Siniestro": 1,
        "Acero": 1
    },
    "Planta": {
        "Normal": 1,
        "Fuego": 0.5,
        "Agua": 2,
        "Planta": 0.5,
        "Eléctrico": 1,
        "Hielo": 1,
        "Lucha": 1,
        "Veneno": 0.5,
        "Tierra": 2,
        "Volador": 0.5,
        "Psíquico": 1,
        "Bicho": 0.5,
        "Roca": 2,
        "Fantasma": 1,
        "Dragón": 0.5,
        "Siniestro": 1,
        "Acero": 0.5
    },
    "Eléctrico": {
        "Normal": 1,
        "Fuego": 1,
        "Agua": 2,
        "Planta": 0.5,
        "Eléctrico": 0.5,
        "Hielo": 1,
        "Lucha": 1,
        "Veneno": 1,
        "Tierra": 0,  # Inmune
        "Volador": 2,
        "Psíquico": 1,
        "Bicho": 1,
        "Roca": 1,
        "Fantasma": 1,
        "Dragón": 0.5,
        "Siniestro": 1,
        "Acero": 1
    },
    "Hielo": {
        "Normal": 1,
        "Fuego": 0.5,
        "Agua": 0.5,
        "Planta": 2,
        "Eléctrico": 1,
        "Hielo": 0.5,
        "Lucha": 1,
        "Veneno": 1,
        "Tierra": 2,
        "Volador": 2,
        "Psíquico": 1,
        "Bicho": 1,
        "Roca": 1,
        "Fantasma": 1,
        "Dragón": 2,
        "Siniestro": 1,
        "Acero": 0.5
    },
    "Lucha": {
        "Normal": 2,
        "Fuego": 1,
        "Agua": 1,
        "Planta": 1,
        "Eléctrico": 1,
        "Hielo": 2,
        "Lucha": 1,
        "Veneno": 0.5,
        "Tierra": 1,
        "Volador": 0.5,
        "Psíquico": 0.5,
        "Bicho": 0.5,
        "Roca": 2,
        "Fantasma": 0,  # Inmune
        "Dragón": 1,
        "Siniestro": 2,
        "Acero": 2
    },
    "Veneno": {
        "Normal": 1,
        "Fuego": 1,
        "Agua": 1,
        "Planta": 2,
        "Eléctrico": 1,
        "Hielo": 1,
        "Lucha": 1,
        "Veneno": 0.5,
        "Tierra": 0.5,
        "Volador": 1,
        "Psíquico": 1,
        "Bicho": 1,
        "Roca": 0.5,
        "Fantasma": 0.5,
        "Dragón": 1,
        "Siniestro": 1,
        "Acero": 0
    },
    "Tierra": {
        "Normal": 1,
        "Fuego": 2,
        "Agua": 1,
        "Planta": 0.5,
        "Eléctrico": 2,
        "Hielo": 1,
        "Lucha": 1,
        "Veneno": 2,
        "Tierra": 1,
        "Volador": 0,  # Inmune
        "Psíquico": 1,
        "Bicho": 0.5,
        "Roca": 2,
        "Fantasma": 1,
        "Dragón": 1,
        "Siniestro": 1,
        "Acero": 2
    },
    "Volador": {
        "Normal": 1,
        "Fuego": 1,
        "Agua": 1,
        "Planta": 2,
        "Eléctrico": 0.5,
        "Hielo": 1,
        "Lucha": 2,
        "Veneno": 1,
        "Tierra": 1,  # volador hace daño a tierra
        "Volador": 1,
        "Psíquico": 1,
        "Bicho": 2,
        "Roca": 0.5,
        "Fantasma": 1,
        "Dragón": 1,
        "Siniestro": 1,
        "Acero": 0.5
    },
    "Psíquico": {
        "Normal": 1,
        "Fuego": 1,
        "Agua": 1,
        "Planta": 1,
        "Eléctrico": 1,
        "Hielo": 1,
        "Lucha": 2,
        "Veneno": 2,
        "Tierra": 1,
        "Volador": 1,
        "Psíquico": 0.5,
        "Bicho": 1,
        "Roca": 1,
        "Fantasma": 1,
        "Dragón": 1,
        "Siniestro": 0,
        "Acero": 0.5
    },
    "Bicho": {
        "Normal": 1,
        "Fuego": 0.5,
        "Agua": 1,
        "Planta": 2,
        "Eléctrico": 1,
        "Hielo": 1,
        "Lucha": 0.5,
        "Veneno": 0.5,
        "Tierra": 1,
        "Volador": 0.5,
        "Psíquico": 2,
        "Bicho": 1,
        "Roca": 1,
        "Fantasma": 0.5,
        "Dragón": 1,
        "Siniestro": 2,
        "Acero": 0.5
    },
    "Roca": {
        "Normal": 1,
        "Fuego": 2,
        "Agua": 1,
        "Planta": 1,
        "Eléctrico": 1,
        "Hielo": 2,
        "Lucha": 0.5,
        "Veneno": 1,
        "Tierra": 0.5,
        "Volador": 2,
        "Psíquico": 1,
        "Bicho": 2,
        "Roca": 1,
        "Fantasma": 1,
        "Dragón": 1,
        "Siniestro": 1,
        "Acero": 0.5
    },
    "Fantasma": {
        "Normal": 0,  # Inmune
        "Fuego": 1,
        "Agua": 1,
        "Planta": 1,
        "Eléctrico": 1,
        "Hielo": 1,
        "Lucha": 1,
        "Veneno": 1,
        "Tierra": 1,
        "Volador": 1,
        "Psíquico": 2,
        "Bicho": 1,
        "Roca": 1,
        "Fantasma": 2,
        "Dragón": 1,
        "Siniestro": 0.5,
        "Acero": 0.5
    },
    "Dragón": {
        "Normal": 1,
        "Fuego": 1,
        "Agua": 1,
        "Planta": 1,
        "Eléctrico": 1,
        "Hielo": 1,
        "Lucha": 1,
        "Veneno": 1,
        "Tierra": 1,
        "Volador": 1,
        "Psíquico": 1,
        "Bicho": 1,
        "Roca": 1,
        "Fantasma": 1,
        "Dragón": 2,
        "Siniestro": 1,
        "Acero": 0.5
    },
    "Siniestro": {
        "Normal": 1,
        "Fuego": 1,
        "Agua": 1,
        "Planta": 1,
        "Eléctrico": 1,
        "Hielo": 1,
        "Lucha": 0.5,    
        "Veneno": 1,
        "Tierra": 1,
        "Volador": 1,
        "Psíquico": 2,    
        "Bicho": 1,
        "Roca": 1,
        "Fantasma": 2,     
        "Dragón": 1,
        "Siniestro": 0.5,
        "Acero": 1
    },
    "Acero": { 
        "Normal": 1,
        "Fuego": 0.5,
        "Agua": 0.5,
        "Planta": 1,
        "Eléctrico": 0.5,
        "Hielo": 2,
        "Lucha": 1,
        "Veneno": 1,
        "Tierra": 1,
        "Volador": 1,
        "Psíquico": 1,
        "Bicho": 1,
        "Roca": 2,
        "Fantasma": 1,
        "Dragón": 1,
        "Acero": 0.5
    }
}

    def calculate_effectivity(self, tipo_ataque: str, tipo_defensor: list) -> float:
        
        # el tipo de defensor es una lista, entonces se calcula la efectividad tomando en cuenta ambos
        # tipos de la persona que defiende.

        # la función devuelve la efectividad del tipo de un movimiento y los tipos del defensor
        efectividad = 1.0
        for tipo in tipo_defensor:
            efectividad *= self.tabla.get(tipo_ataque, {}).get(tipo, 1.0)  # Default 1 si no existe
        return efectividad